#!/bin/bash

export GSUID=1000
export GSGID=1000
(
  cd `dirname $0`
  (
    docker build . -f rproxy/Dockerfile -t rfielding/rproxy
  )
  (
    cd tika
    docker build . -t rfielding/tika
  )
  (
    cd react/init/ui
    npm run build
  )
  go mod tidy
  go mod vendor
  (
    # this can take a long, long time
    # but on a clean checkout, this dir may  not exist
    cd react/init/ui
    if [ -d build ]
    then
	    npm install
    fi
  )
  docker build -t rfielding/microcms:latest .
)
