#!/bin/bash

(
  cd `dirname $0`
  ./build
  killall gosqlite
  rm -rf files; mkdir files ; ./setup.sh ; cat schema.sql | sqlite3 ; ./build 
  ./gosqlite &  java -jar ./bin/tika-server-standard.jar
)
