#!/bin/bash

  
(
  cd `dirname $0`
  if [ -d persistent ]
  then
    echo using existing persistent dir
  else
    sudo mkdir persistent/prometheus 2>&1 > /dev/null
    sudo chmod -R 777 persistent
  fi 
  docker build . -f rproxy/Dockerfile -t rfielding/rproxy
  docker build . -f tika/Dockerfile -t rfielding/tika
  docker build . -f prometheus/Dockerfile -t rfielding/prometheus
  docker build . -f ./Dockerfile -t rfielding/microcms:latest 
  if [ "$1" == "up" ]
  then
    docker-compose up -d
  fi
)
