version: '3.2'

services:
  microcms:
    image: microcms:latest
    user: 0:0 # oh no. temp hack using user 1000 is not portable, even when it matches user on host in Linux
    ports:
      - '9321:9321'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - DOC_EXTRACTOR=http://tika:9998/tika
    volumes:
      - ./persistent:/root/persistent   # persistent data, which you can wipe before startup
      - ./config.json:/root/config.json # the user database, which hot-reloads
    depends_on:
      - tika
    networks:
      - mesh

  tika:
    image: tika
    user: 0:0
    environment:
      - host=0.0.0.0
    ports:
      - 9998:9998
    networks:
      - mesh
 
  prometheus:
    image: prom/prometheus
    user: 0:0
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090  
    networks:
      - mesh


networks:
  mesh: {}
    
