version: '3.2'

services:
  gosqlite:
    networks:
      mesh:
        aliases:
          - gosqlite
    image: gosqlite:latest
    user: 1000:1000
    ports:
      - '9321:9321'
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/visionbot-secret-key.json
    volumes:
      #- ./schema.db:/root/schema.db
      #- ./files:/root/files
      #- ./visionbot-secret-key.json:/root/visionbot-secret-key.json
      - ./config.json:/root/config.json
networks:
  mesh: {}
    
