version: '3.2'

services:
  microcms:
    image: rfielding/microcms:latest
    user: 0:0 # oh no. temp hack using user 1000 is not portable, even when it matches user on host in Linux
    ports:
      - '9321:9321'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - DOC_EXTRACTOR=http://tika:9998/tika
    volumes:
      - ./persistent:/root/persistent   # persistent data, which you can wipe before startup
      - ./config.json:/root/config.json # the user database, which hot-reloads
    depends_on:
      - tika
    networks:
      - mesh

  tika:
    image: rfielding/tika
    user: 0:0
    environment:
      - host=0.0.0.0
    ports:
      - 9998:9998
    networks:
      - mesh
 
  prometheus:
    image: prom/prometheus
    user: 0:0
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090  
    networks:
      - mesh

  rproxy:
    image: rfielding/rproxy
    user: 0:0
    ports:
      - 443:443
    environment:
      - RPROXY0=/files@http://microcms:9321/files
      - RPROXY1=/me@http://microcms:9321/me
      - RPROXY2=/registration@http://microcms:9321/registration
      - RPROXY3=/search@http://microcms:9321/search
      - RPROXY4=/prometheus@http://prometheus:9090/
      - RPROXY5=/@http://localhost:3000/
      - X509_CERT=/root/rproxy/cert.pem
      - X509_KEY=/root/rproxy/key.pem
      - BIND=0.0.0.0:443
    depends_on:
      - microcms
    volumes:
      - ./certs/cert.pem:/root/rproxy/cert.pem
      - ./certs/key.pem:/root/rproxy/key.pem
      - ./react/init/ui:/root/ui
    networks:
      - mesh

networks:
  mesh: {}
    
