version: '3.2'

services:
  microcms:
    image: microcms:latest
    user: 1000:1000
    ports:
      - '9321:9321'
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./persistent:/root/persistent   # persistent data, which you can wipe before startup
      - ./config.json:/root/config.json # the user database, which hot-reloads
    networks:
      - mesh

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090  
    networks:
      - mesh


networks:
  mesh: {}
    
