version: '3.2'

services:
  microcms:
    networks:
      mesh:
        aliases:
          - microcms
    image: microcms:latest
    user: 1000:1000
    ports:
      - '9321:9321'
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./persistent:/root/persistent   # persistent data, which you can wipe before startup
      - ./config.json:/root/config.json # the user database

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090  


networks:
  mesh: {}
    
