version: '3.2'

services:
  gosqlite:
    networks:
      mesh:
        aliases:
          - gosqlite
    image: gosqlite:latest
    user: 1000:1000
    ports:
      - '9321:9321'
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
    volumes:
      #- ./schema.db:/root/schema.db
      #- ./files:/root/files
      - ./config.json:/root/config.json
networks:
  mesh: {}
    
