global:
  scrape_interval:     15s 
  external_labels:
    monitor: 'microcms'
scrape_configs:
  - job_name: 'microcms\'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['microcms:9321']