#!/bin/bash

(
open http://localhost:8080/registration/?account=5ee5de77d0c566d2b8c170a03894ff2d
echo user2 http://localhost:8080/registration/?account=33b98226f52c0e39e8f94cb565becd7d

export RPROXY0="/registration@http://localhost:9321/registration" 
export RPROXY1="/files@http://localhost:9321/files" 
export RPROXY2="/search@http://localhost:9321/search" 
export RPROXY3="/me@http://localhost:9321/me" 
export RPROXY4="/@http://localhost:3000/" 
go run cmd/rproxy/main.go 
)
