#!/bin/bash

# bring up compose, and build npm, wait for 2 sec before proxy comes up
# because npm build clears the screen
(
export RPROXY0="/registration@http://localhost:9321/registration" 
export RPROXY1="/files@http://localhost:9321/files" 
export RPROXY2="/search@http://localhost:9321/search" 
export RPROXY3="/me@http://localhost:9321/me" 
export RPROXY4="/@http://localhost:3000/" 
export BROWSER=none
export PUBLIC_URL="." 

(cd media/init/ui; npm start) & ( sleep 2 ; docker-compose up -d ) & (  sleep 2; go run cmd/rproxy/main.go )

sleep 8
# a macos-ism
open http://localhost:8080/registration/?account=5ee5de77d0c566d2b8c170a03894ff2d
echo or login via: http://localhost:8080/registration/?account=33b98226f52c0e39e8f94cb565becd7d
)