#!/bin/bash

url=http://localhost:9321

(
  cd `dirname $0`

  # This is the private cookie for a user
  auth=5ee5de77d0c566d2b8c170a03894ff2d
  # this is the first email address of that user
  owner=$(curl --cookie "account=${auth}" ${url}/me | jq -r '.email[0]')

  # Put in a html app
  ( cd app && tar cvf ../app.tar . ) 
  curl -X POST --cookie "account=${auth}" --data-binary @app.tar ${url}/files/${owner}/app/v1?install=true
  rm app.tar

  # Put in a js app
  ( cd brl && tar cvf ../brl.tar . ) 
  curl -X POST --cookie "account=${auth}" --data-binary @brl.tar ${url}/files/${owner}/brl?install=true
  rm brl.tar

  ( cd dbg && tar cvf ../dbg.tar . )
  curl -X POST --cookie "account=${auth}" --data-binary @dbg.tar ${url}/files/${owner}/gateways?install=true
  rm dbg.tar

  ( cd Gilgamesh && tar cvf ../gilgamesh.tar . )
  curl -X POST --cookie "account=${auth}" --data-binary @gilgamesh.tar ${url}/files/${owner}/gilgamesh?install=true
  rm gilgamesh.tar

  ( cd kjv-bible && tar cvf ../kjv-bible.tar . )
  curl -X POST --cookie "account=${auth}" --data-binary @kjv-bible.tar ${url}/files/${owner}/kjv-bible?install=true
  rm kjv-bible.tar

  if [ -d react-test/build ]
  then
    echo build exists for react app
  else
    export PUBLIC_URL="."
    npx create-react-app react-test
    (cd react-test && npm run build)
  fi
  ( cd react-test/build && tar cvf ../../react-test.tar . ) 
  curl -X POST --cookie "account=${auth}" --data-binary @react-test.tar ${url}/files/${owner}/app/react-test?install=true
  rm react-test.tar

  for f in *.pdf
  do
    curl -X POST --cookie "account=${auth}" --data-binary @${f} ${url}/files/${owner}/documents/${f}
  done
  for f in *.json
  do
    curl -X POST --cookie "account=${auth}" --data-binary @${f} ${url}/files/${owner}/documents/${f}
  done
  for f in *.txt
  do
    curl -X POST --cookie "account=${auth}" --data-binary @${f} ${url}/files/${owner}/documents/${f}
  done
  for f in *.jpg
  do
    curl -X POST --cookie "account=${auth}" --data-binary @${f} ${url}/files/${owner}/documents/${f}
  done
  for f in *.mp4
  do
    curl -X POST --cookie "account=${auth}" --data-binary @${f} ${url}/files/${owner}/documents/${f}
  done
  for f in *.png
  do
    curl -X POST --cookie "account=${auth}" --data-binary @${f} ${url}/files/${owner}/documents/${f}
  done
)

curl 'http://localhost:9321/search?json=true&match=king' | jq
