#!/bin/bash

# Put in a React app
(
  cd `dirname $0`
  ( cd app && tar cvf ../app.tar . ) 
  curl -X POST --data-binary @app.tar http://localhost:9321/files/app/v1?install=true
  #rm app.tar
)

# Put in an html app
(
  cd `dirname $0`
  ( cd react-test/build && tar cvf ../../react-test.tar . ) 
  curl -X POST --data-binary @react-test.tar http://localhost:9321/files/app/react-test?install=true
  #rm react-test.tar
)

# Put in random files
(
  cd `dirname $0`
  for f in *.pdf
  do
    curl -X POST --data-binary @${f} http://localhost:9321/files/documents/${f}
  done
  for f in *.txt
  do
    curl -X POST --data-binary @${f} http://localhost:9321/files/documents/${f}
  done
  for f in *.jpg
  do
    curl -X POST --data-binary @${f} http://localhost:9321/files/documents/${f}
  done
  for f in *.mp4
  do
    curl -X POST --data-binary @${f} http://localhost:9321/files/documents/${f}
  done
)
